_Connecting to Python 3.14.3..._

In [ ]:
# =============================================================
#  PARTE 1: PREPARAÇÃO PARA ANÁLISE POR EVENTO
#  Define os 8 eventos do REDATA e prepara o DataFrame de preços
# =============================================================

# Dicionário com os 8 eventos: código -> data
EVENTOS = {
    "E1": "2025-07-18",  # MP 1.307 (ZPEs)
    "E2": "2025-09-17",  # MP 1.318 (REDATA) - edição
    "E3": "2025-09-18",  # MP 1.318 - publicação DOU
    "E4": "2026-02-04",  # Protocolo do PL 278/2026
    "E5": "2026-02-10",  # Urgência aprovada na Câmara
    "E6": "2026-02-25",  # PL aprovado na Câmara (madrugada 24-25)
    "E7": "2026-02-25",  # Senado não vota
    "E8": "2026-02-25",  # Caducidade da MP
}

# Converte a coluna 'data' do DataFrame pra tipo datetime do pandas
df_precos["data"] = pd.to_datetime(df_precos["data"])

# Mostra o que ficou
print(f"Eventos definidos: {len(EVENTOS)}")
for cod, data in EVENTOS.items():
    print(f"  {cod}: {data}")
print(f"\nDataFrame de preços: {len(df_precos)} linhas")
print(f"Colunas: {list(df_precos.columns)}")

In [ ]:
import requests
import pandas as pd
from datetime import date, timedelta

# ----- CONFIGURAÇÃO -----
BASE_URL = "https://laboratoriodefinancas.com/api/v2"
TOKEN   = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgxNzQzNjUwLCJpYXQiOjE3NzkxNTE2NTAsImp0aSI6Ijg5NDM1MTEyZTU2ZjQ2ZGNhOTE4NzFiMDA3M2YzMGMyIiwidXNlcl9pZCI6IjEwMSJ9.0RvfbPUc3L1dwU04C7owFlZ1pObMs6bQobLcMx7lKnM"
HEADERS = {"Authorization": f"Bearer {TOKEN}"}

In [ ]:
# ----- CONFIGURAÇÃO -----
BASE_URL = "https://laboratoriodefinancas.com/api/v2"
TOKEN   = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgxNzQzNjUwLCJpYXQiOjE3NzkxNTE2NTAsImp0aSI6Ijg5NDM1MTEyZTU2ZjQ2ZGNhOTE4NzFiMDA3M2YzMGMyIiwidXNlcl9pZCI6IjEwMSJ9.0RvfbPUc3L1dwU04C7owFlZ1pObMs6bQobLcMx7lKnM"
HEADERS = {"Authorization": f"Bearer {TOKEN}"}

Connected to Python 3.14.3

In [ ]:
#  energia, mineração e siderurgia + Ibovespa
# =============================================================
import requests
import pandas as pd
from datetime import date, timedelta

# ----- CONFIGURAÇÃO -----
BASE_URL = "https://laboratoriodefinancas.com/api/v2"
TOKEN   = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgxNzQzNjUwLCJpYXQiOjE3NzkxNTE2NTAsImp0aSI6Ijg5NDM1MTEyZTU2ZjQ2ZGNhOTE4NzFiMDA3M2YzMGMyIiwidXNlcl9pZCI6IjEwMSJ9.0RvfbPUc3L1dwU04C7owFlZ1pObMs6bQobLcMx7lKnM"
HEADERS = {"Authorization": f"Bearer {TOKEN}"}

In [ ]:
# Lista de ações por setor
TICKERS = {
    "Energia":             ["AXIA3", "EGIE3", "TAEE11", "CPLE3", "CMIG4", "EQTL3", "ISAE4", "NEOE3"],
    "Siderurgia e metais": ["GGBR4", "CSNA3", "USIM5", "CBAV3"],
    "Mineração":           ["VALE3", "CMIN3", "AURA33"],
}

# Período de coleta
DATA_INI = "2025-03-01"
DATA_FIM = "2026-05-15"

# Lista plana de todos os tickers (junta tudo em uma lista só)
todos_tickers = [t for setor in TICKERS.values() for t in setor]
print(f"Total de ações a coletar: {len(todos_tickers)}")
print(f"Tickers: {todos_tickers}")

# %%
# ----- BUSCAR PREÇOS DE TODAS AS AÇÕES -----
lista_dfs = []  # vai guardar um DataFrame por ação

for ticker in todos_tickers:
    params = {
        "ticker":   ticker,
        "data_ini": DATA_INI,
        "data_fim": DATA_FIM,
    }

    resp = requests.get(
        f"{BASE_URL}/preco/corrigido",
        headers=HEADERS,
        params=params,
    )

    if resp.status_code == 200:
        dados = resp.json()
        if len(dados) > 0:
            df_temp = pd.DataFrame(dados)
            lista_dfs.append(df_temp)
            print(f"✅ {ticker}: {len(dados)} registros")
        else:
            print(f"⚠️  {ticker}: sem dados no período")
    else:
        print(f"❌ {ticker}: erro {resp.status_code}")

Total de ações a coletar: 15
Tickers: ['AXIA3', 'EGIE3', 'TAEE11', 'CPLE3', 'CMIG4', 'EQTL3', 'ISAE4', 'NEOE3', 'GGBR4', 'CSNA3', 'USIM5', 'CBAV3', 'VALE3', 'CMIN3', 'AURA33']
✅ AXIA3: 299 registros
✅ EGIE3: 299 registros
✅ TAEE11: 299 registros
✅ CPLE3: 299 registros
✅ CMIG4: 299 registros
✅ EQTL3: 299 registros
✅ ISAE4: 299 registros
✅ NEOE3: 290 registros
✅ GGBR4: 299 registros
✅ CSNA3: 299 registros
✅ USIM5: 299 registros
✅ CBAV3: 299 registros
✅ VALE3: 299 registros
✅ CMIN3: 299 registros
✅ AURA33: 299 registros

In [ ]:
# =============================================================
#  COLETA DO IBOVESPA (BENCHMARK)
#  Endpoint diferente: /preco/diversos (índices e outros)
# =============================================================
params_ibov = {
    "ticker":   "IBOV",
    "data_ini": DATA_INI,
    "data_fim": DATA_FIM,
}

resp = requests.get(
    f"{BASE_URL}/preco/diversos",
    headers=HEADERS,
    params=params_ibov,
)

df_ibov = pd.DataFrame(resp.json())

print(f"Total de registros do Ibovespa: {len(df_ibov)}")
print(f"Primeira data: {df_ibov['data'].min()}")
print(f"Última data:   {df_ibov['data'].max()}")
print()
df_ibov.head()

Total de registros do Ibovespa: 238
Primeira data: 2025-06-02
Última data:   2026-05-15

,ticker,nome,data,abertura,maximo,minimo,medio,fechamento
0,ibov,IBovespa,2025-06-02,137026.0000,138471.0000,136483.0000,0.0000,136787.0000
1,ibov,IBovespa,2025-06-03,136787.0000,137672.0000,136175.0000,0.0000,137546.0000
2,ibov,IBovespa,2025-06-04,137547.0000,138797.0000,136695.0000,0.0000,137002.0000
3,ibov,IBovespa,2025-06-05,137003.0000,137451.0000,136031.0000,0.0000,136236.0000
4,ibov,IBovespa,2025-06-06,136236.0000,136890.0000,135601.0000,0.0000,136102.0000

In [ ]:
# =============================================================
#  PARTE 1: PREPARAÇÃO PARA ANÁLISE POR EVENTO
#  Define os 8 eventos do REDATA e prepara o DataFrame de preços
# =============================================================

# Dicionário com os 8 eventos: código -> data
EVENTOS = {
    "E1": "2025-07-18",  # MP 1.307 (ZPEs)
    "E2": "2025-09-17",  # MP 1.318 (REDATA) - edição
    "E3": "2025-09-18",  # MP 1.318 - publicação DOU
    "E4": "2026-02-04",  # Protocolo do PL 278/2026
    "E5": "2026-02-10",  # Urgência aprovada na Câmara
    "E6": "2026-02-25",  # PL aprovado na Câmara (madrugada 24-25)
    "E7": "2026-02-25",  # Senado não vota
    "E8": "2026-02-25",  # Caducidade da MP
}

# Converte a coluna 'data' do DataFrame pra tipo datetime do pandas
df_precos["data"] = pd.to_datetime(df_precos["data"])

# Mostra o que ficou
print(f"Eventos definidos: {len(EVENTOS)}")
for cod, data in EVENTOS.items():
    print(f"  {cod}: {data}")
print(f"\nDataFrame de preços: {len(df_precos)} linhas")
print(f"Colunas: {list(df_precos.columns)}")

NameError: name 'df_precos' is not defined

In [ ]:
# =============================================================
#  JUNTAR TODAS AS AÇÕES NUM ÚNICO DATAFRAME
# =============================================================
df_precos = pd.concat(lista_dfs, ignore_index=True)

print(f"DataFrame único criado: df_precos")
print(f"Total de linhas: {len(df_precos)}")
print(f"Ações distintas: {df_precos['ticker'].nunique()}")
print(f"Colunas: {list(df_precos.columns)}")
df_precos.head()

DataFrame único criado: df_precos
Total de linhas: 4476
Ações distintas: 15
Colunas: ['ticker', 'data', 'abertura', 'maximo', 'minimo', 'medio', 'fechamento', 'volume']

,ticker,data,abertura,maximo,minimo,medio,fechamento,volume
0,AXIA3,2025-03-05,28.00845088,28.02289939,27.36549185,27.58221961,27.62556517,249506848
1,AXIA3,2025-03-06,27.50997703,28.40578510,27.39438889,28.04457217,27.93620829,295827449
2,AXIA3,2025-03-07,27.79172312,28.39133659,27.41606167,28.10236624,28.16016031,298659369
3,AXIA3,2025-03-10,27.96510532,28.47080343,27.93620829,28.28297271,28.36966381,413770495
4,AXIA3,2025-03-11,28.25407567,28.31186974,27.75560182,28.01567514,28.16738457,227451345

In [ ]:
# =============================================================
#  PARTE 1: PREPARAÇÃO PARA ANÁLISE POR EVENTO
#  Define os 8 eventos do REDATA e prepara o DataFrame de preços
# =============================================================

# Dicionário com os 8 eventos: código -> data
EVENTOS = {
    "E1": "2025-07-18",  # MP 1.307 (ZPEs)
    "E2": "2025-09-17",  # MP 1.318 (REDATA) - edição
    "E3": "2025-09-18",  # MP 1.318 - publicação DOU
    "E4": "2026-02-04",  # Protocolo do PL 278/2026
    "E5": "2026-02-10",  # Urgência aprovada na Câmara
    "E6": "2026-02-25",  # PL aprovado na Câmara (madrugada 24-25)
    "E7": "2026-02-25",  # Senado não vota
    "E8": "2026-02-25",  # Caducidade da MP
}

# Converte a coluna 'data' do DataFrame pra tipo datetime do pandas
df_precos["data"] = pd.to_datetime(df_precos["data"])

# Mostra o que ficou
print(f"Eventos definidos: {len(EVENTOS)}")
for cod, data in EVENTOS.items():
    print(f"  {cod}: {data}")
print(f"\nDataFrame de preços: {len(df_precos)} linhas")
print(f"Colunas: {list(df_precos.columns)}")

Eventos definidos: 8
  E1: 2025-07-18
  E2: 2025-09-17
  E3: 2025-09-18
  E4: 2026-02-04
  E5: 2026-02-10
  E6: 2026-02-25
  E7: 2026-02-25
  E8: 2026-02-25

DataFrame de preços: 4476 linhas
Colunas: ['ticker', 'data', 'abertura', 'maximo', 'minimo', 'medio', 'fechamento', 'volume']

In [ ]:
# =============================================================
#  PARTE 2: FUNÇÃO QUE GERA A TABELA DE UM SETOR NUM EVENTO
#  Recebe: nome do setor + código do evento
#  Retorna: tabela com 11 linhas (dias -5 a +5)
#           e colunas Abertura/Fechamento de cada ação
# =============================================================

def gerar_tabela_setor_evento(nome_setor, codigo_evento):
    # PASSO 1: pegar a data do evento e a lista de ações do setor
    data_evento = pd.to_datetime(EVENTOS[codigo_evento])
    tickers_setor = TICKERS[nome_setor]

    # PASSO 2: pegar todas as datas distintas do df_precos (só dias de pregão)
    datas_pregao = sorted(df_precos["data"].unique())

    # PASSO 3: achar o índice do dia do evento na lista de pregões
    # (se o evento caiu num dia sem pregão, pega o próximo dia útil)
    idx_evento = None
    for i in range(len(datas_pregao)):
        if datas_pregao[i] >= data_evento:
            idx_evento = i
            break

    # PASSO 4: pegar os 11 dias da janela (-5 a +5)
    idx_inicio = idx_evento - 5
    idx_fim = idx_evento + 5
    datas_janela = datas_pregao[idx_inicio : idx_fim + 1]

    # PASSO 5: filtrar o df_precos pra ter só essas datas e essas ações
    df_filtrado = df_precos[
        (df_precos["data"].isin(datas_janela)) &
        (df_precos["ticker"].isin(tickers_setor))
    ]

    # PASSO 6: reorganizar com pivot (uma linha por data, colunas por ação)
    tabela = df_filtrado.pivot(
        index="data",
        columns="ticker",
        values=["abertura", "fechamento"]
    )

    # PASSO 7: adicionar a coluna "Dia" com -5, -4, ..., +5
    tabela["Dia"] = range(-5, 6)

    # PASSO 8: reordenar pra "Dia" vir primeiro
    colunas = ["Dia"] + [c for c in tabela.columns if c != "Dia"]
    tabela = tabela[colunas]

    # IMPRESSÃO COM DESTAQUE NO DIA 0
    print("=" * 100)
    print(f"SETOR: {nome_setor.upper()}    |    EVENTO: {codigo_evento} ({EVENTOS[codigo_evento]})")
    print("=" * 100)
    print(tabela)
    print("=" * 100)
    print(f"⭐ Linha em destaque: dia 0 = data do evento ({data_evento.strftime('%d/%m/%Y')})")
    print()

    return tabela


# TESTE: gerar uma tabela pra ver se funciona
tabela_teste = gerar_tabela_setor_evento("Energia", "E5")

KeyError: "[('abertura', 'AXIA3') ('abertura', 'CMIG4') ('abertura', 'CPLE3')\n ('abertura', 'EGIE3') ('abertura', 'EQTL3') ('abertura', 'ISAE4')\n ('abertura', 'NEOE3') ('abertura', 'TAEE11') ('fechamento', 'AXIA3')\n ('fechamento', 'CMIG4') ('fechamento', 'CPLE3') ('fechamento', 'EGIE3')\n ('fechamento', 'EQTL3') ('fechamento', 'ISAE4') ('fechamento', 'NEOE3')\n ('fechamento', 'TAEE11') ('Dia', '')] not in index"

In [ ]:
# =============================================================
#  PARTE 2: FUNÇÃO QUE GERA A TABELA DE UM SETOR NUM EVENTO
#  Recebe: nome do setor + código do evento
#  Retorna: tabela com 11 linhas (dias -5 a +5)
#           e colunas Abertura/Fechamento de cada ação
# =============================================================

def gerar_tabela_setor_evento(nome_setor, codigo_evento):
    # PASSO 1: pegar a data do evento e a lista de ações do setor
    data_evento = pd.to_datetime(EVENTOS[codigo_evento])
    tickers_setor = TICKERS[nome_setor]

    # PASSO 2: pegar todas as datas distintas do df_precos (só dias de pregão)
    datas_pregao = sorted(df_precos["data"].unique())

    # PASSO 3: achar o índice do dia do evento na lista de pregões
    # (se o evento caiu num dia sem pregão, pega o próximo dia útil)
    idx_evento = None
    for i in range(len(datas_pregao)):
        if datas_pregao[i] >= data_evento:
            idx_evento = i
            break

    # PASSO 4: pegar os 11 dias da janela (-5 a +5)
    idx_inicio = idx_evento - 5
    idx_fim = idx_evento + 5
    datas_janela = datas_pregao[idx_inicio : idx_fim + 1]

    # PASSO 5: filtrar o df_precos pra ter só essas datas e essas ações
    df_filtrado = df_precos[
        (df_precos["data"].isin(datas_janela)) &
        (df_precos["ticker"].isin(tickers_setor))
    ]

    # PASSO 6: reorganizar com pivot (uma linha por data, colunas por ação)
    tabela = df_filtrado.pivot(
        index="data",
        columns="ticker",
        values=["abertura", "fechamento"]
    )

    # PASSO 7: simplificar nomes das colunas (juntar os 2 níveis em 1)
    # Ex: ("abertura", "AXIA3") vira "AXIA3_abertura"
    tabela.columns = [f"{ticker}_{valor}" for valor, ticker in tabela.columns]

    # PASSO 8: ordenar colunas: cada ação aparece junto (abertura + fechamento)
    tickers_ordenados = sorted(tickers_setor)
    colunas_ordenadas = []
    for t in tickers_ordenados:
        colunas_ordenadas.append(f"{t}_abertura")
        colunas_ordenadas.append(f"{t}_fechamento")
    tabela = tabela[colunas_ordenadas]

    # PASSO 9: adicionar coluna "Dia" no início (-5 a +5)
    tabela.insert(0, "Dia", range(-5, 6))

    # IMPRESSÃO COM DESTAQUE NO DIA 0
    print("=" * 100)
    print(f"SETOR: {nome_setor.upper()}    |    EVENTO: {codigo_evento} ({EVENTOS[codigo_evento]})")
    print("=" * 100)
    print(tabela)
    print("=" * 100)
    print(f"⭐ Linha em destaque: dia 0 = data do evento ({data_evento.strftime('%d/%m/%Y')})")
    print()

    return tabela


# TESTE: gerar uma tabela pra ver se funciona
tabela_teste = gerar_tabela_setor_evento("Energia", "E5")

====================================================================================================
SETOR: ENERGIA    |    EVENTO: E5 (2026-02-10)
====================================================================================================
            Dia AXIA3_abertura AXIA3_fechamento CMIG4_abertura  \
data
2026-02-03   -5    56.46000000      56.74000000    11.28410108
2026-02-04   -4    56.57000000      54.98000000    11.36138945
2026-02-05   -3    55.43000000      56.90000000    11.16816853
2026-02-06   -2    57.10000000      57.63000000    11.16816853
2026-02-09   -1    57.96000000      58.63000000    10.96528658
2026-02-10    0    58.59000000      58.85000000    11.04257494
2026-02-11    1    59.61000000      59.55000000    11.11020227
2026-02-12    2    59.36000000      58.89000000    11.51596617
2026-02-13    3    57.67000000      58.43000000    11.36138945
2026-02-18    4    58.61000000      58.58000000    11.41935571
2026-02-19    5    59.15000000      61.18000000    11.29376212

           CMIG4_fechamento CPLE3_abertura CPLE3_fechamento EGIE3_abertura  \
data
2026-02-03      11.43867781    13.07585856      13.37213934    33.13201046
2026-02-04      11.16816853    13.38201537      13.00672637    33.17145333
2026-02-05      11.13918540    13.05610650      13.17461882    32.84604966
2026-02-06      10.96528658    13.21412292      13.23387497    32.95451755
2026-02-09      11.03291389    13.28325510      13.54990781    32.96437827
2026-02-10      11.06189704    13.51040370      13.81656051    32.91507468
2026-02-11      11.51596617    13.92519680      13.98445296    33.45741414
2026-02-12      11.44833885    13.92519680      13.78693244    34.47306803
2026-02-13      11.36138945    13.63879204      13.79680846    32.95451755
2026-02-18      11.26477899    13.88569270      13.90544475    33.07284616
2026-02-19      11.46766094    13.93507283      14.10296527    32.92493540

           EGIE3_fechamento EQTL3_abertura EQTL3_fechamento ISAE4_abertura  \
data
2026-02-03      33.30950338    41.21000000      41.21000000    28.15350036
2026-02-04      32.78688536    41.28000000      40.26000000    28.34921466
2026-02-05      32.84604966    40.55000000      40.43000000    27.88928608
2026-02-06      32.88549253    40.43000000      40.89000000    28.48621466
2026-02-09      32.98409970    40.89000000      41.41000000    28.36878608
2026-02-10      33.30950338    41.40000000      41.38000000    28.81892895
2026-02-11      34.48292875    41.85000000      42.05000000    29.09292894
2026-02-12      33.65462849    41.86000000      41.37000000    29.45500039
2026-02-13      33.23061764    40.93000000      41.00000000    29.14185751
2026-02-18      32.80660679    41.20000000      40.85000000    28.96571467
2026-02-19      33.25033907    40.96000000      41.27000000    29.01464324

           ISAE4_fechamento NEOE3_abertura NEOE3_fechamento TAEE11_abertura  \
data
2026-02-03      28.47642895    32.45000000      32.45000000     40.90522042
2026-02-04      27.71314322    32.47000000      32.46000000     40.91489755
2026-02-05      28.48621466    32.46000000      32.48000000     40.16975868
2026-02-06      28.31007179    32.48000000      32.50000000     40.35362412
2026-02-09      28.82871466    32.50000000      32.57000000     40.37297838
2026-02-10      28.83850037    32.55000000      32.64000000     41.19553426
2026-02-11      29.45500039    32.65000000      32.66000000     41.32133693
2026-02-12      29.66050038    32.76000000      32.70000000     42.57936358
2026-02-13      28.96571467    32.68000000      32.72000000     42.28904974
2026-02-18      28.81892895    32.70000000      32.74000000     42.09550718
2026-02-19      29.07335752    32.72000000      32.75000000     42.26969548

           TAEE11_fechamento
data
2026-02-03       41.01166883
2026-02-04       40.14072731
2026-02-05       40.35362412
2026-02-06       40.16975868
2026-02-09       41.07940873
2026-02-10       41.20521139
2026-02-11       42.98580296
2026-02-12       42.45356091
2026-02-13       42.19227845
2026-02-18       42.26969548
2026-02-19       43.12128275
====================================================================================================
⭐ Linha em destaque: dia 0 = data do evento (10/02/2026)

In [ ]:
# =============================================================
#  PARTE 3: GERAR ARQUIVO EXCEL COM TODAS AS TABELAS
#  8 abas (1 por evento) × 3 tabelas dentro (1 por setor)
#  = 24 tabelas no total, com destaque visual no dia 0
# =============================================================
from openpyxl import Workbook
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side

# Nome do arquivo de saída
NOME_ARQUIVO = "tabelas_redata.xlsx"

# Estilos para destaque do dia 0
fill_evento = PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid")  # amarelo
font_evento = Font(bold=True, color="9C5700")  # texto marrom escuro em negrito
font_cabecalho_setor = Font(bold=True, size=12, color="FFFFFF")  # texto branco em negrito
fill_cabecalho_setor = PatternFill(start_color="2E74B5", end_color="2E74B5", fill_type="solid")  # azul
font_cabecalho_tabela = Font(bold=True)
fill_cabecalho_tabela = PatternFill(start_color="D9D9D9", end_color="D9D9D9", fill_type="solid")  # cinza

# Borda fina
borda_fina = Border(
    left=Side(style="thin", color="BFBFBF"),
    right=Side(style="thin", color="BFBFBF"),
    top=Side(style="thin", color="BFBFBF"),
    bottom=Side(style="thin", color="BFBFBF"),
)

# Criar arquivo Excel
wb = Workbook()
wb.remove(wb.active)  # remove a aba padrão "Sheet"

# Loop pelos 8 eventos
for codigo_evento, data_evento in EVENTOS.items():
    # Criar uma aba pra esse evento
    ws = wb.create_sheet(title=codigo_evento)

    # Linha atual onde vai escrever (começa na 1)
    linha_atual = 1

    # Cabeçalho geral da aba
    ws.cell(row=linha_atual, column=1, value=f"EVENTO {codigo_evento} — {data_evento}")
    ws.cell(row=linha_atual, column=1).font = Font(bold=True, size=14)
    linha_atual += 2  # pula linha em branco

    # Loop pelos 3 setores
    for nome_setor in TICKERS.keys():
        # Gerar a tabela desse setor nesse evento
        tabela = gerar_tabela_setor_evento(nome_setor, codigo_evento)

        # ---- ESCREVER O CABEÇALHO DO SETOR ----
        ws.cell(row=linha_atual, column=1, value=f"SETOR: {nome_setor.upper()}")
        ws.cell(row=linha_atual, column=1).font = font_cabecalho_setor
        ws.cell(row=linha_atual, column=1).fill = fill_cabecalho_setor
        linha_atual += 1

        # ---- ESCREVER OS CABEÇALHOS DAS COLUNAS ----
        ws.cell(row=linha_atual, column=1, value="Dia")
        ws.cell(row=linha_atual, column=2, value="Data")
        col = 3
        for nome_coluna in tabela.columns:
            if nome_coluna == "Dia":
                continue  # já escrevemos
            ws.cell(row=linha_atual, column=col, value=nome_coluna)
            col += 1
        # Aplicar estilo nos cabeçalhos
        for c in range(1, col):
            ws.cell(row=linha_atual, column=c).font = font_cabecalho_tabela
            ws.cell(row=linha_atual, column=c).fill = fill_cabecalho_tabela
            ws.cell(row=linha_atual, column=c).border = borda_fina
            ws.cell(row=linha_atual, column=c).alignment = Alignment(horizontal="center")
        linha_atual += 1

        # ---- ESCREVER OS DADOS ----
        for idx_linha, (data, linha) in enumerate(tabela.iterrows()):
            dia = linha["Dia"]
            data_str = data.strftime("%d/%m/%Y")

            # Coluna 1: Dia
            ws.cell(row=linha_atual, column=1, value=int(dia))
            # Coluna 2: Data
            ws.cell(row=linha_atual, column=2, value=data_str)
            # Demais colunas: valores
            col = 3
            for nome_coluna in tabela.columns:
                if nome_coluna == "Dia":
                    continue
                valor = linha[nome_coluna]
                ws.cell(row=linha_atual, column=col, value=round(float(valor), 4))
                col += 1

            # Aplicar estilo (destaque se for dia 0)
            for c in range(1, col):
                ws.cell(row=linha_atual, column=c).border = borda_fina
                ws.cell(row=linha_atual, column=c).alignment = Alignment(horizontal="center")
                if dia == 0:
                    ws.cell(row=linha_atual, column=c).fill = fill_evento
                    ws.cell(row=linha_atual, column=c).font = font_evento

            linha_atual += 1

        # Pula 2 linhas entre as tabelas dos setores
        linha_atual += 2

    # Ajustar largura das colunas da aba
    for col_idx in range(1, 20):
        ws.column_dimensions[chr(64 + col_idx) if col_idx <= 26 else "A"].width = 14

    print(f"✅ Aba '{codigo_evento}' criada")

# Salvar arquivo
wb.save(NOME_ARQUIVO)
print(f"\n📁 Arquivo salvo: {NOME_ARQUIVO}")
print(f"   8 abas (uma por evento)")
print(f"   3 tabelas por aba (uma por setor)")
print(f"   Total: 24 tabelas")

====================================================================================================
SETOR: ENERGIA    |    EVENTO: E1 (2025-07-18)
====================================================================================================
            Dia AXIA3_abertura AXIA3_fechamento CMIG4_abertura  \
data
2025-07-11   -5    28.97484890      28.98959813     9.93275128
2025-07-14   -4    28.96747429      28.55449604     9.94196534
2025-07-15   -3    28.73148672      28.97484890     9.89589507
2025-07-16   -2    29.04122041      28.87897895     9.82218263
2025-07-17   -1    28.81998206      28.86422973     9.69318585
2025-07-18    0    28.57661988      28.73148672     9.60104531
2025-07-21    1    28.92322662      28.81260745     9.60104531
2025-07-22    2    28.85685512      28.49549915     9.68397180
2025-07-23    3    28.45125148      28.59874371     9.54576098
2025-07-24    4    28.52499760      28.35538153     9.72082803
2025-07-25    5    28.39225459      28.12676857     9.69318585

           CMIG4_fechamento CPLE3_abertura CPLE3_fechamento EGIE3_abertura  \
data
2025-07-11       9.95117940    10.30765132      10.32624041    28.97746630
2025-07-14       9.82218263    10.28906223      10.23329496    28.55132708
2025-07-15       9.78532642    10.33553496      10.35412406    29.36923943
2025-07-16       9.69318585    10.34482951      10.49354224    28.73003061
2025-07-17       9.63790153    10.50283679      10.39130224    28.86749488
2025-07-18       9.56418908    10.31694587      10.32624041    28.31076463
2025-07-21       9.65632965    10.32624041      10.31694587    28.73690383
2025-07-22       9.53654692    10.35412406      10.14034950    28.92248058
2025-07-23       9.74847019    10.09387677      10.31694587    28.58569314
2025-07-24       9.70239990    10.24258950      10.16823314    29.20428232
2025-07-25       9.65632965    10.14964405      10.12176041    29.15616983

           EGIE3_fechamento EQTL3_abertura EQTL3_fechamento ISAE4_abertura  \
data
2025-07-11      28.57881993    33.03244979      33.15793834    21.48463867
2025-07-14      29.21115554    32.97453199      32.96487902    21.46577595
2025-07-15      28.68191813    33.06140869      33.27377394    21.45634457
2025-07-16      28.66129850    33.33169174      33.16759131    21.47520730
2025-07-17      28.37262354    33.21585614      33.33169174    21.50350136
2025-07-18      28.66817170    33.07106165      33.03244979    21.22056059
2025-07-21      28.84687524    33.19655021      33.14828538    21.17340378
2025-07-22      28.59256636    33.24481504      32.75251377    21.22056059
2025-07-23      29.23177517    32.80077860      33.39926249    20.93761978
2025-07-24      29.25926804    33.06140869      32.96487902    21.15454105
2025-07-25      28.97059308    33.19655021      32.70424894    21.11681562

           ISAE4_fechamento NEOE3_abertura NEOE3_fechamento TAEE11_abertura  \
data
2025-07-11      21.50350136    23.66993440      23.57264737     31.64454877
2025-07-14      21.44691323    23.56291867      23.25160017     31.63527429
2025-07-15      21.39975641    23.25160017      23.42671682     31.44051006
2025-07-16      21.50350136    23.32942979      23.38780201     31.34776520
2025-07-17      21.24885466    23.40725942      23.35861590     31.26429481
2025-07-18      21.16397240    23.35861590      22.86245205     30.97678572
2025-07-21      21.29601144    23.06675481      22.81380854     31.34776520
2025-07-22      20.92818841    22.92082427      22.56086226     31.34776520
2025-07-23      21.16397240    22.86245205      23.82559365     31.02315816
2025-07-24      21.12624696    23.81586494      23.47536034     31.25502032
2025-07-25      21.09795287    23.55318996      23.15431314     31.19009893

           TAEE11_fechamento
data
2025-07-11       31.53325493
2025-07-14       31.42196109
2025-07-15       31.25502032
2025-07-16       31.33849070
2025-07-17       31.14372649
2025-07-18       31.35703969
2025-07-21       31.33849070
2025-07-22       30.94896226
2025-07-23       31.25502032
2025-07-24       31.13445200
2025-07-25       31.06025610
====================================================================================================
⭐ Linha em destaque: dia 0 = data do evento (18/07/2025)

====================================================================================================
SETOR: SIDERURGIA E METAIS    |    EVENTO: E1 (2025-07-18)
====================================================================================================
            Dia CBAV3_abertura CBAV3_fechamento CSNA3_abertura  \
data
2025-07-11   -5     4.78015805       4.87974467     8.35000000
2025-07-14   -4     4.87974467       4.63077811     8.29000000
2025-07-15   -3     4.68057142       4.64073677     8.22000000
2025-07-16   -2     4.65069543       4.59094346     8.15000000
2025-07-17   -1     4.60090212       4.66065410     8.02000000
2025-07-18    0     4.65069543       4.48139817     7.81000000
2025-07-21    1     4.50131550       4.54115015     7.86000000
2025-07-22    2     4.54115015       4.72040607     8.10000000
2025-07-23    3     4.70048875       4.75028206     8.47000000
2025-07-24    4     4.68057142       4.69053008     8.66000000
2025-07-25    5     4.69053008       4.72040607     8.50000000

           CSNA3_fechamento GGBR4_abertura GGBR4_fechamento USIM5_abertura  \
data
2025-07-11       8.25000000    16.18374914      16.11615591     4.30000000
2025-07-14       8.20000000    16.34790411      16.07753122     4.27000000
2025-07-15       8.08000000    16.02925034      15.90372008     4.21000000
2025-07-16       8.00000000    15.88440772      15.96165713     4.07000000
2025-07-17       7.91000000    16.00993800      15.78784597     4.01000000
2025-07-18       7.82000000    15.65265952      15.55609777     4.01000000
2025-07-21       7.99000000    15.70094040      16.04856270     3.95000000
2025-07-22       8.56000000    16.18374914      16.32859177     4.06000000
2025-07-23       8.77000000    16.28031090      16.62793318     4.24000000
2025-07-24       8.55000000    16.55068379      16.68587024     4.30000000
2025-07-25       8.37000000    16.52171526      16.58930849     4.28000000

           USIM5_fechamento
data
2025-07-11       4.29000000
2025-07-14       4.22000000
2025-07-15       4.20000000
2025-07-16       4.01000000
2025-07-17       4.03000000
2025-07-18       3.92000000
2025-07-21       4.01000000
2025-07-22       4.25000000
2025-07-23       4.36000000
2025-07-24       4.28000000
2025-07-25       4.20000000
====================================================================================================
⭐ Linha em destaque: dia 0 = data do evento (18/07/2025)

====================================================================================================
SETOR: MINERAÇÃO    |    EVENTO: E1 (2025-07-18)
====================================================================================================
            Dia AURA33_abertura AURA33_fechamento CMIN3_abertura  \
data
2025-07-11   -5     49.44959503       49.29658912     4.79489639
2025-07-14   -4     49.29658912       47.14494363     4.81355358
2025-07-15   -3     46.85805757       45.42362723     4.75758202
2025-07-16   -2     46.09302806       43.04247288     4.77623920
2025-07-17   -1     43.56843066       43.37717329     4.81355358
2025-07-18    0     43.37717329       42.93728132     4.73892483
2025-07-21    1     43.03291001       44.46734034     4.76691061
2025-07-22    2     44.70641206       45.27062133     4.99079682
2025-07-23    3     45.17499264       44.27608297     4.90683949
2025-07-24    4     44.25695723       43.85531674     4.98146823
2025-07-25    5     43.70231082       44.68728633     4.89751090

           CMIN3_fechamento VALE3_abertura VALE3_fechamento
data
2025-07-11       4.80422498    51.11349847      51.85427381
2025-07-14       4.76691061    51.72463813      51.26165354
2025-07-15       4.73892483    50.86348679      49.91899823
2025-07-16       4.80422498    50.09493238      50.37272314
2025-07-17       4.76691061    50.37272314      50.28012622
2025-07-18       4.70161046    50.04863392      50.52087820
2025-07-21       4.92549668    51.34499077      51.90057227
2025-07-22       4.97213964    52.73394453      53.24322757
2025-07-23       5.00945401    53.19692912      53.16915004
2025-07-24       4.93482528    52.72468484      52.34503747
2025-07-25       4.82288217    52.02094826      51.57648306
====================================================================================================
⭐ Linha em destaque: dia 0 = data do evento (18/07/2025)

✅ Aba 'E1' criada
====================================================================================================
SETOR: ENERGIA    |    EVENTO: E2 (2025-09-17)
====================================================================================================
            Dia AXIA3_abertura AXIA3_fechamento CMIG4_abertura  \
data
2025-09-10   -5    34.79650925      35.04225815    10.16310267
2025-09-11   -4    35.11905469      35.55679493    10.22760105
2025-09-12   -3    35.03457850      35.55679493    10.11703240
2025-09-15   -2    35.74110661      36.63194639    10.16310267
2025-09-16   -1    37.03128837      36.83161738    10.28288539
2025-09-17    0    36.64730570      37.47670826    10.32895566
2025-09-18    1    37.39991173      37.63030133    10.50402269
2025-09-19    2    38.04500261      38.82064759    10.44873837
2025-09-22    3    38.45970389      38.19859567    10.38423998
2025-09-23    4    38.19859567      38.93584239    10.40266810
2025-09-24    5    38.87440517      38.93584239    10.58694920

           CMIG4_fechamento CPLE3_abertura CPLE3_fechamento EGIE3_abertura  \
data
2025-09-10      10.19995888    10.63296043      10.70731680    28.15724110
2025-09-11      10.17231671    10.70731680      10.74449498    28.76156422
2025-09-12      10.08939023    10.69802225      10.78167316    28.31183539
2025-09-15      10.22760105    10.80955681      10.92109135    28.36102447
2025-09-16      10.31052753    10.93968044      10.96756408    28.65615902
2025-09-17      10.50402269    10.96756408      11.15345500    28.48048369
2025-09-18      10.41188215    11.15345500      11.12557136    28.60696994
2025-09-19      10.40266810    11.13486591      11.32075682    28.78967228
2025-09-22      10.39345405    11.31146228      11.16274954    29.14102293
2025-09-23      10.52245082    11.18133863      11.31146228    29.19723903
2025-09-24      10.55009297    11.33005137      11.21851681    28.90913150

           EGIE3_fechamento EQTL3_abertura EQTL3_fechamento ISAE4_abertura  \
data
2025-09-10      28.50859175    34.93408410      35.18506122    21.78644219
2025-09-11      28.50859175    35.18506122      35.16575528    21.90904987
2025-09-12      28.38210552    34.81824850      34.91477816    21.82416763
2025-09-15      28.61399695    35.19471418      35.29124385    22.03165756
2025-09-16      28.43129461    35.66770952      34.99200190    21.97506937
2025-09-17      28.65615902    35.07887858      35.38777350    22.08824571
2025-09-18      28.80372630    35.29124385      35.33950867    22.25801020
2025-09-19      29.30264422    35.34916163      35.89938070    22.28630428
2025-09-22      29.01453669    35.47465020      35.31054977    22.44663742
2025-09-23      28.97940163    35.35881460      35.94764553    22.18255933
2025-09-24      28.52967279    35.89938070      35.63875062    22.50322556

           ISAE4_fechamento NEOE3_abertura NEOE3_fechamento TAEE11_abertura  \
data
2025-09-10      21.90904987    27.44467116      27.42521376     33.11745148
2025-09-11      21.93734394    28.22296740      28.07703686     33.16489768
2025-09-12      21.93734394    28.12568037      28.30079703     33.06051603
2025-09-15      21.93734394    28.21323870      28.21323870     33.20285465
2025-09-16      22.10710844    28.22296740      27.78517577     33.23132238
2025-09-17      22.42777468    27.78517577      27.97002113     33.48753189
2025-09-18      22.27687292    27.97002113      27.72680355     33.72476291
2025-09-19      22.58810781    27.86300539      27.87273410     33.63935973
2025-09-22      22.19199068    27.81436188      28.01866464     33.78169836
2025-09-23      22.50322556    27.94083502      28.03812205     33.89556925
2025-09-24      22.47493149    27.98947853      27.66843133     34.23718193

           TAEE11_fechamento
data
2025-09-10       33.11745148
2025-09-11       33.06051603
2025-09-12       33.06051603
2025-09-15       33.22183314
2025-09-16       33.48753189
2025-09-17       33.72476291
2025-09-18       33.63935973
2025-09-19       33.98097243
2025-09-22       33.87659076
2025-09-23       34.25616042
2025-09-24       34.19922497
====================================================================================================
⭐ Linha em destaque: dia 0 = data do evento (17/09/2025)

====================================================================================================
SETOR: SIDERURGIA E METAIS    |    EVENTO: E2 (2025-09-17)
====================================================================================================
            Dia CBAV3_abertura CBAV3_fechamento CSNA3_abertura  \
data
2025-09-10   -5     3.81416778       3.71458115     7.79000000
2025-09-11   -4     3.73449848       3.73449848     7.76000000
2025-09-12   -3     3.73449848       3.78429179     7.72000000
2025-09-15   -2     3.78429179       3.72453981     7.86000000
2025-09-16   -1     3.74445714       3.87391975     7.93000000
2025-09-17    0     3.90379574       3.85400243     8.04000000
2025-09-18    1     3.87391975       3.79425045     8.11000000
2025-09-19    2     3.79425045       3.85400243     7.94000000
2025-09-22    3     3.80420911       3.71458115     8.04000000
2025-09-23    4     3.70462249       3.79425045     7.94000000
2025-09-24    5     3.79425045       3.73449848     7.98000000

           CSNA3_fechamento GGBR4_abertura GGBR4_fechamento USIM5_abertura  \
data
2025-09-10       7.75000000    16.58396380      16.45751715     4.52000000
2025-09-11       7.82000000    16.54505714      16.53533047     4.48000000
2025-09-12       7.83000000    16.35052384      15.85446392     4.54000000
2025-09-15       7.87000000    15.93227724      16.24353052     4.54000000
2025-09-16       8.07000000    16.36025049      16.32134385     4.56000000
2025-09-17       8.11000000    16.24353052      16.37970383     4.59000000
2025-09-18       7.91000000    16.33107051      16.35052384     4.62000000
2025-09-19       8.01000000    16.35052384      16.31161718     4.42000000
2025-09-22       7.95000000    16.24353052      16.28243719     4.48000000
2025-09-23       7.98000000    16.30189051      16.39915716     4.42000000
2025-09-24       8.04000000    16.38943050      16.24353052     4.42000000

           USIM5_fechamento
data
2025-09-10       4.47000000
2025-09-11       4.54000000
2025-09-12       4.52000000
2025-09-15       4.53000000
2025-09-16       4.59000000
2025-09-17       4.63000000
2025-09-18       4.38000000
2025-09-19       4.50000000
2025-09-22       4.44000000
2025-09-23       4.44000000
2025-09-24       4.45000000
====================================================================================================
⭐ Linha em destaque: dia 0 = data do evento (17/09/2025)

====================================================================================================
SETOR: MINERAÇÃO    |    EVENTO: E2 (2025-09-17)
====================================================================================================
            Dia AURA33_abertura AURA33_fechamento CMIN3_abertura  \
data
2025-09-10   -5     55.96237516       57.83069180     4.81355358
2025-09-11   -4     57.84037219       57.91781537     4.69228188
2025-09-12   -3     57.91781537       56.53351859     4.69228188
2025-09-15   -2     56.77552851       55.98173596     4.74825343
2025-09-16   -1     56.63032255       54.78136673     4.77623920
2025-09-17    0     54.69424316       54.27798608     4.81355358
2025-09-18    1     54.59743918       53.09697765     4.82288217
2025-09-19    2     52.56455581       56.14630271     4.83221076
2025-09-22    3     56.43671462       58.87617467     4.84153934
2025-09-23    4     59.05042181       60.65736772     4.87885372
2025-09-24    5     60.90905804       59.29243174     4.98146823

           CMIN3_fechamento VALE3_abertura VALE3_fechamento
data
2025-09-10       4.71093905    53.84351028      53.94839404
2025-09-11       4.72959624    53.82444050      54.36792910
2025-09-12       4.75758202    54.06281269      54.34885932
2025-09-15       4.74825343    54.80653392      54.82560370
2025-09-16       4.82288217    55.08304567      55.01630145
2025-09-17       4.86019653    54.86374325      55.11165033
2025-09-18       4.82288217    55.14978988      55.00676656
2025-09-19       4.86019653    55.27374342      55.22606898
2025-09-22       4.89751090    55.13072010      55.30234808
2025-09-23       5.00012542    55.30234808      54.98769679
2025-09-24       4.97213964    55.25467364      55.19746432
====================================================================================================
⭐ Linha em destaque: dia 0 = data do evento (17/09/2025)

✅ Aba 'E2' criada
====================================================================================================
SETOR: ENERGIA    |    EVENTO: E3 (2025-09-18)
====================================================================================================
            Dia AXIA3_abertura AXIA3_fechamento CMIG4_abertura  \
data
2025-09-11   -5    35.11905469      35.55679493    10.22760105
2025-09-12   -4    35.03457850      35.55679493    10.11703240
2025-09-15   -3    35.74110661      36.63194639    10.16310267
2025-09-16   -2    37.03128837      36.83161738    10.28288539
2025-09-17   -1    36.64730570      37.47670826    10.32895566
2025-09-18    0    37.39991173      37.63030133    10.50402269
2025-09-19    1    38.04500261      38.82064759    10.44873837
2025-09-22    2    38.45970389      38.19859567    10.38423998
2025-09-23    3    38.19859567      38.93584239    10.40266810
2025-09-24    4    38.87440517      38.93584239    10.58694920
2025-09-25    5    38.99727962      38.70545279    10.55930703

           CMIG4_fechamento CPLE3_abertura CPLE3_fechamento EGIE3_abertura  \
data
2025-09-11      10.17231671    10.70731680      10.74449498    28.76156422
2025-09-12      10.08939023    10.69802225      10.78167316    28.31183539
2025-09-15      10.22760105    10.80955681      10.92109135    28.36102447
2025-09-16      10.31052753    10.93968044      10.96756408    28.65615902
2025-09-17      10.50402269    10.96756408      11.15345500    28.48048369
2025-09-18      10.41188215    11.15345500      11.12557136    28.60696994
2025-09-19      10.40266810    11.13486591      11.32075682    28.78967228
2025-09-22      10.39345405    11.31146228      11.16274954    29.14102293
2025-09-23      10.52245082    11.18133863      11.31146228    29.19723903
2025-09-24      10.55009297    11.33005137      11.21851681    28.90913150
2025-09-25      10.30131349    11.19992772      11.02333135    28.47345668

           EGIE3_fechamento EQTL3_abertura EQTL3_fechamento ISAE4_abertura  \
data
2025-09-11      28.50859175    35.18506122      35.16575528    21.90904987
2025-09-12      28.38210552    34.81824850      34.91477816    21.82416763
2025-09-15      28.61399695    35.19471418      35.29124385    22.03165756
2025-09-16      28.43129461    35.66770952      34.99200190    21.97506937
2025-09-17      28.65615902    35.07887858      35.38777350    22.08824571
2025-09-18      28.80372630    35.29124385      35.33950867    22.25801020
2025-09-19      29.30264422    35.34916163      35.89938070    22.28630428
2025-09-22      29.01453669    35.47465020      35.31054977    22.44663742
2025-09-23      28.97940163    35.35881460      35.94764553    22.18255933

In [ ]:
# =============================================================
#  PARTE 3: GERAR ARQUIVO EXCEL COM TODAS AS TABELAS
#  8 abas (1 por evento) × 3 tabelas dentro (1 por setor)
#  = 24 tabelas no total, com destaque visual no dia 0
# =============================================================
from openpyxl import Workbook
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side

# Nome do arquivo de saída
NOME_ARQUIVO = "tabelas_redata.xlsx"

# Estilos para destaque do dia 0
fill_evento = PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid")  # amarelo
font_evento = Font(bold=True, color="9C5700")  # texto marrom escuro em negrito
font_cabecalho_setor = Font(bold=True, size=12, color="FFFFFF")  # texto branco em negrito
fill_cabecalho_setor = PatternFill(start_color="2E74B5", end_color="2E74B5", fill_type="solid")  # azul
font_cabecalho_tabela = Font(bold=True)
fill_cabecalho_tabela = PatternFill(start_color="D9D9D9", end_color="D9D9D9", fill_type="solid")  # cinza

# Borda fina
borda_fina = Border(
    left=Side(style="thin", color="BFBFBF"),
    right=Side(style="thin", color="BFBFBF"),
    top=Side(style="thin", color="BFBFBF"),
    bottom=Side(style="thin", color="BFBFBF"),
)

# Criar arquivo Excel
wb = Workbook()
wb.remove(wb.active)  # remove a aba padrão "Sheet"

# Loop pelos 8 eventos
for codigo_evento, data_evento in EVENTOS.items():
    # Criar uma aba pra esse evento
    ws = wb.create_sheet(title=codigo_evento)

    # Linha atual onde vai escrever (começa na 1)
    linha_atual = 1

    # Cabeçalho geral da aba
    ws.cell(row=linha_atual, column=1, value=f"EVENTO {codigo_evento} — {data_evento}")
    ws.cell(row=linha_atual, column=1).font = Font(bold=True, size=14)
    linha_atual += 2  # pula linha em branco

    # Loop pelos 3 setores
    for nome_setor in TICKERS.keys():
        # Gerar a tabela desse setor nesse evento
        tabela = gerar_tabela_setor_evento(nome_setor, codigo_evento)

        # ---- ESCREVER O CABEÇALHO DO SETOR ----
        ws.cell(row=linha_atual, column=1, value=f"SETOR: {nome_setor.upper()}")
        ws.cell(row=linha_atual, column=1).font = font_cabecalho_setor
        ws.cell(row=linha_atual, column=1).fill = fill_cabecalho_setor
        linha_atual += 1

        # ---- ESCREVER OS CABEÇALHOS DAS COLUNAS ----
        ws.cell(row=linha_atual, column=1, value="Dia")
        ws.cell(row=linha_atual, column=2, value="Data")
        col = 3
        for nome_coluna in tabela.columns:
            if nome_coluna == "Dia":
                continue  # já escrevemos
            ws.cell(row=linha_atual, column=col, value=nome_coluna)
            col += 1
        # Aplicar estilo nos cabeçalhos
        for c in range(1, col):
            ws.cell(row=linha_atual, column=c).font = font_cabecalho_tabela
            ws.cell(row=linha_atual, column=c).fill = fill_cabecalho_tabela
            ws.cell(row=linha_atual, column=c).border = borda_fina
            ws.cell(row=linha_atual, column=c).alignment = Alignment(horizontal="center")
        linha_atual += 1

        # ---- ESCREVER OS DADOS ----
        for idx_linha, (data, linha) in enumerate(tabela.iterrows()):
            dia = linha["Dia"]
            data_str = data.strftime("%d/%m/%Y")

            # Coluna 1: Dia
            ws.cell(row=linha_atual, column=1, value=int(dia))
            # Coluna 2: Data
            ws.cell(row=linha_atual, column=2, value=data_str)
            # Demais colunas: valores
            col = 3
            for nome_coluna in tabela.columns:
                if nome_coluna == "Dia":
                    continue
                valor = linha[nome_coluna]
                ws.cell(row=linha_atual, column=col, value=round(float(valor), 4))
                col += 1

            # Aplicar estilo (destaque se for dia 0)
            for c in range(1, col):
                ws.cell(row=linha_atual, column=c).border = borda_fina
                ws.cell(row=linha_atual, column=c).alignment = Alignment(horizontal="center")
                if dia == 0:
                    ws.cell(row=linha_atual, column=c).fill = fill_evento
                    ws.cell(row=linha_atual, column=c).font = font_evento

            linha_atual += 1

        # Pula 2 linhas entre as tabelas dos setores
        linha_atual += 2

    # Ajustar largura das colunas da aba
    for col_idx in range(1, 20):
        ws.column_dimensions[chr(64 + col_idx) if col_idx <= 26 else "A"].width = 14

    print(f"✅ Aba '{codigo_evento}' criada")

# Salvar arquivo
wb.save(NOME_ARQUIVO)
print(f"\n📁 Arquivo salvo: {NOME_ARQUIVO}")
print(f"   8 abas (uma por evento)")
print(f"   3 tabelas por aba (uma por setor)")
print(f"   Total: 24 tabelas")

====================================================================================================
SETOR: ENERGIA    |    EVENTO: E1 (2025-07-18)
====================================================================================================
            Dia AXIA3_abertura AXIA3_fechamento CMIG4_abertura  \
data
2025-07-11   -5    28.97484890      28.98959813     9.93275128
2025-07-14   -4    28.96747429      28.55449604     9.94196534
2025-07-15   -3    28.73148672      28.97484890     9.89589507
2025-07-16   -2    29.04122041      28.87897895     9.82218263
2025-07-17   -1    28.81998206      28.86422973     9.69318585
2025-07-18    0    28.57661988      28.73148672     9.60104531
2025-07-21    1    28.92322662      28.81260745     9.60104531
2025-07-22    2    28.85685512      28.49549915     9.68397180
2025-07-23    3    28.45125148      28.59874371     9.54576098
2025-07-24    4    28.52499760      28.35538153     9.72082803
2025-07-25    5    28.39225459      28.12676857     9.69318585

           CMIG4_fechamento CPLE3_abertura CPLE3_fechamento EGIE3_abertura  \
data
2025-07-11       9.95117940    10.30765132      10.32624041    28.97746630
2025-07-14       9.82218263    10.28906223      10.23329496    28.55132708
2025-07-15       9.78532642    10.33553496      10.35412406    29.36923943
2025-07-16       9.69318585    10.34482951      10.49354224    28.73003061
2025-07-17       9.63790153    10.50283679      10.39130224    28.86749488
2025-07-18       9.56418908    10.31694587      10.32624041    28.31076463
2025-07-21       9.65632965    10.32624041      10.31694587    28.73690383
2025-07-22       9.53654692    10.35412406      10.14034950    28.92248058
2025-07-23       9.74847019    10.09387677      10.31694587    28.58569314
2025-07-24       9.70239990    10.24258950      10.16823314    29.20428232
2025-07-25       9.65632965    10.14964405      10.12176041    29.15616983

           EGIE3_fechamento EQTL3_abertura EQTL3_fechamento ISAE4_abertura  \
data
2025-07-11      28.57881993    33.03244979      33.15793834    21.48463867
2025-07-14      29.21115554    32.97453199      32.96487902    21.46577595
2025-07-15      28.68191813    33.06140869      33.27377394    21.45634457
2025-07-16      28.66129850    33.33169174      33.16759131    21.47520730
2025-07-17      28.37262354    33.21585614      33.33169174    21.50350136
2025-07-18      28.66817170    33.07106165      33.03244979    21.22056059
2025-07-21      28.84687524    33.19655021      33.14828538    21.17340378
2025-07-22      28.59256636    33.24481504      32.75251377    21.22056059
2025-07-23      29.23177517    32.80077860      33.39926249    20.93761978
2025-07-24      29.25926804    33.06140869      32.96487902    21.15454105
2025-07-25      28.97059308    33.19655021      32.70424894    21.11681562

           ISAE4_fechamento NEOE3_abertura NEOE3_fechamento TAEE11_abertura  \
data
2025-07-11      21.50350136    23.66993440      23.57264737     31.64454877
2025-07-14      21.44691323    23.56291867      23.25160017     31.63527429
2025-07-15      21.39975641    23.25160017      23.42671682     31.44051006
2025-07-16      21.50350136    23.32942979      23.38780201     31.34776520
2025-07-17      21.24885466    23.40725942      23.35861590     31.26429481
2025-07-18      21.16397240    23.35861590      22.86245205     30.97678572
2025-07-21      21.29601144    23.06675481      22.81380854     31.34776520
2025-07-22      20.92818841    22.92082427      22.56086226     31.34776520
2025-07-23      21.16397240    22.86245205      23.82559365     31.02315816
2025-07-24      21.12624696    23.81586494      23.47536034     31.25502032
2025-07-25      21.09795287    23.55318996      23.15431314     31.19009893

           TAEE11_fechamento
data
2025-07-11       31.53325493
2025-07-14       31.42196109
2025-07-15       31.25502032
2025-07-16       31.33849070
2025-07-17       31.14372649
2025-07-18       31.35703969
2025-07-21       31.33849070
2025-07-22       30.94896226
2025-07-23       31.25502032
2025-07-24       31.13445200
2025-07-25       31.06025610
====================================================================================================
⭐ Linha em destaque: dia 0 = data do evento (18/07/2025)

====================================================================================================
SETOR: SIDERURGIA E METAIS    |    EVENTO: E1 (2025-07-18)
====================================================================================================
            Dia CBAV3_abertura CBAV3_fechamento CSNA3_abertura  \
data
2025-07-11   -5     4.78015805       4.87974467     8.35000000
2025-07-14   -4     4.87974467       4.63077811     8.29000000
2025-07-15   -3     4.68057142       4.64073677     8.22000000
2025-07-16   -2     4.65069543       4.59094346     8.15000000
2025-07-17   -1     4.60090212       4.66065410     8.02000000
2025-07-18    0     4.65069543       4.48139817     7.81000000
2025-07-21    1     4.50131550       4.54115015     7.86000000
2025-07-22    2     4.54115015       4.72040607     8.10000000
2025-07-23    3     4.70048875       4.75028206     8.47000000
2025-07-24    4     4.68057142       4.69053008     8.66000000
2025-07-25    5     4.69053008       4.72040607     8.50000000

           CSNA3_fechamento GGBR4_abertura GGBR4_fechamento USIM5_abertura  \
data
2025-07-11       8.25000000    16.18374914      16.11615591     4.30000000
2025-07-14       8.20000000    16.34790411      16.07753122     4.27000000
2025-07-15       8.08000000    16.02925034      15.90372008     4.21000000
2025-07-16       8.00000000    15.88440772      15.96165713     4.07000000
2025-07-17       7.91000000    16.00993800      15.78784597     4.01000000
2025-07-18       7.82000000    15.65265952      15.55609777     4.01000000
2025-07-21       7.99000000    15.70094040      16.04856270     3.95000000
2025-07-22       8.56000000    16.18374914      16.32859177     4.06000000
2025-07-23       8.77000000    16.28031090      16.62793318     4.24000000
2025-07-24       8.55000000    16.55068379      16.68587024     4.30000000
2025-07-25       8.37000000    16.52171526      16.58930849     4.28000000

           USIM5_fechamento
data
2025-07-11       4.29000000
2025-07-14       4.22000000
2025-07-15       4.20000000
2025-07-16       4.01000000
2025-07-17       4.03000000
2025-07-18       3.92000000
2025-07-21       4.01000000
2025-07-22       4.25000000
2025-07-23       4.36000000
2025-07-24       4.28000000
2025-07-25       4.20000000
====================================================================================================
⭐ Linha em destaque: dia 0 = data do evento (18/07/2025)

====================================================================================================
SETOR: MINERAÇÃO    |    EVENTO: E1 (2025-07-18)
====================================================================================================
            Dia AURA33_abertura AURA33_fechamento CMIN3_abertura  \
data
2025-07-11   -5     49.44959503       49.29658912     4.79489639
2025-07-14   -4     49.29658912       47.14494363     4.81355358
2025-07-15   -3     46.85805757       45.42362723     4.75758202
2025-07-16   -2     46.09302806       43.04247288     4.77623920
2025-07-17   -1     43.56843066       43.37717329     4.81355358
2025-07-18    0     43.37717329       42.93728132     4.73892483
2025-07-21    1     43.03291001       44.46734034     4.76691061
2025-07-22    2     44.70641206       45.27062133     4.99079682
2025-07-23    3     45.17499264       44.27608297     4.90683949
2025-07-24    4     44.25695723       43.85531674     4.98146823
2025-07-25    5     43.70231082       44.68728633     4.89751090

           CMIN3_fechamento VALE3_abertura VALE3_fechamento
data
2025-07-11       4.80422498    51.11349847      51.85427381
2025-07-14       4.76691061    51.72463813      51.26165354
2025-07-15       4.73892483    50.86348679      49.91899823
2025-07-16       4.80422498    50.09493238      50.37272314
2025-07-17       4.76691061    50.37272314      50.28012622
2025-07-18       4.70161046    50.04863392      50.52087820
2025-07-21       4.92549668    51.34499077      51.90057227
2025-07-22       4.97213964    52.73394453      53.24322757
2025-07-23       5.00945401    53.19692912      53.16915004
2025-07-24       4.93482528    52.72468484      52.34503747
2025-07-25       4.82288217    52.02094826      51.57648306
====================================================================================================
⭐ Linha em destaque: dia 0 = data do evento (18/07/2025)

✅ Aba 'E1' criada
====================================================================================================
SETOR: ENERGIA    |    EVENTO: E2 (2025-09-17)
====================================================================================================
            Dia AXIA3_abertura AXIA3_fechamento CMIG4_abertura  \
data
2025-09-10   -5    34.79650925      35.04225815    10.16310267
2025-09-11   -4    35.11905469      35.55679493    10.22760105
2025-09-12   -3    35.03457850      35.55679493    10.11703240
2025-09-15   -2    35.74110661      36.63194639    10.16310267
2025-09-16   -1    37.03128837      36.83161738    10.28288539
2025-09-17    0    36.64730570      37.47670826    10.32895566
2025-09-18    1    37.39991173      37.63030133    10.50402269
2025-09-19    2    38.04500261      38.82064759    10.44873837
2025-09-22    3    38.45970389      38.19859567    10.38423998
2025-09-23    4    38.19859567      38.93584239    10.40266810
2025-09-24    5    38.87440517      38.93584239    10.58694920

           CMIG4_fechamento CPLE3_abertura CPLE3_fechamento EGIE3_abertura  \
data
2025-09-10      10.19995888    10.63296043      10.70731680    28.15724110
2025-09-11      10.17231671    10.70731680      10.74449498    28.76156422
2025-09-12      10.08939023    10.69802225      10.78167316    28.31183539
2025-09-15      10.22760105    10.80955681      10.92109135    28.36102447
2025-09-16      10.31052753    10.93968044      10.96756408    28.65615902
2025-09-17      10.50402269    10.96756408      11.15345500    28.48048369
2025-09-18      10.41188215    11.15345500      11.12557136    28.60696994
2025-09-19      10.40266810    11.13486591      11.32075682    28.78967228
2025-09-22      10.39345405    11.31146228      11.16274954    29.14102293
2025-09-23      10.52245082    11.18133863      11.31146228    29.19723903
2025-09-24      10.55009297    11.33005137      11.21851681    28.90913150

           EGIE3_fechamento EQTL3_abertura EQTL3_fechamento ISAE4_abertura  \
data
2025-09-10      28.50859175    34.93408410      35.18506122    21.78644219
2025-09-11      28.50859175    35.18506122      35.16575528    21.90904987
2025-09-12      28.38210552    34.81824850      34.91477816    21.82416763
2025-09-15      28.61399695    35.19471418      35.29124385    22.03165756
2025-09-16      28.43129461    35.66770952      34.99200190    21.97506937
2025-09-17      28.65615902    35.07887858      35.38777350    22.08824571
2025-09-18      28.80372630    35.29124385      35.33950867    22.25801020
2025-09-19      29.30264422    35.34916163      35.89938070    22.28630428
2025-09-22      29.01453669    35.47465020      35.31054977    22.44663742
2025-09-23      28.97940163    35.35881460      35.94764553    22.18255933
2025-09-24      28.52967279    35.89938070      35.63875062    22.50322556

           ISAE4_fechamento NEOE3_abertura NEOE3_fechamento TAEE11_abertura  \
data
2025-09-10      21.90904987    27.44467116      27.42521376     33.11745148
2025-09-11      21.93734394    28.22296740      28.07703686     33.16489768
2025-09-12      21.93734394    28.12568037      28.30079703     33.06051603
2025-09-15      21.93734394    28.21323870      28.21323870     33.20285465
2025-09-16      22.10710844    28.22296740      27.78517577     33.23132238
2025-09-17      22.42777468    27.78517577      27.97002113     33.48753189
2025-09-18      22.27687292    27.97002113      27.72680355     33.72476291
2025-09-19      22.58810781    27.86300539      27.87273410     33.63935973
2025-09-22      22.19199068    27.81436188      28.01866464     33.78169836
2025-09-23      22.50322556    27.94083502      28.03812205     33.89556925
2025-09-24      22.47493149    27.98947853      27.66843133     34.23718193

           TAEE11_fechamento
data
2025-09-10       33.11745148
2025-09-11       33.06051603
2025-09-12       33.06051603
2025-09-15       33.22183314
2025-09-16       33.48753189
2025-09-17       33.72476291
2025-09-18       33.63935973
2025-09-19       33.98097243
2025-09-22       33.87659076
2025-09-23       34.25616042
2025-09-24       34.19922497
====================================================================================================
⭐ Linha em destaque: dia 0 = data do evento (17/09/2025)

====================================================================================================
SETOR: SIDERURGIA E METAIS    |    EVENTO: E2 (2025-09-17)
====================================================================================================
            Dia CBAV3_abertura CBAV3_fechamento CSNA3_abertura  \
data
2025-09-10   -5     3.81416778       3.71458115     7.79000000
2025-09-11   -4     3.73449848       3.73449848     7.76000000
2025-09-12   -3     3.73449848       3.78429179     7.72000000
2025-09-15   -2     3.78429179       3.72453981     7.86000000
2025-09-16   -1     3.74445714       3.87391975     7.93000000
2025-09-17    0     3.90379574       3.85400243     8.04000000
2025-09-18    1     3.87391975       3.79425045     8.11000000
2025-09-19    2     3.79425045       3.85400243     7.94000000
2025-09-22    3     3.80420911       3.71458115     8.04000000
2025-09-23    4     3.70462249       3.79425045     7.94000000
2025-09-24    5     3.79425045       3.73449848     7.98000000

           CSNA3_fechamento GGBR4_abertura GGBR4_fechamento USIM5_abertura  \
data
2025-09-10       7.75000000    16.58396380      16.45751715     4.52000000
2025-09-11       7.82000000    16.54505714      16.53533047     4.48000000
2025-09-12       7.83000000    16.35052384      15.85446392     4.54000000
2025-09-15       7.87000000    15.93227724      16.24353052     4.54000000
2025-09-16       8.07000000    16.36025049      16.32134385     4.56000000
2025-09-17       8.11000000    16.24353052      16.37970383     4.59000000
2025-09-18       7.91000000    16.33107051      16.35052384     4.62000000
2025-09-19       8.01000000    16.35052384      16.31161718     4.42000000
2025-09-22       7.95000000    16.24353052      16.28243719     4.48000000
2025-09-23       7.98000000    16.30189051      16.39915716     4.42000000
2025-09-24       8.04000000    16.38943050      16.24353052     4.42000000

           USIM5_fechamento
data
2025-09-10       4.47000000
2025-09-11       4.54000000
2025-09-12       4.52000000
2025-09-15       4.53000000
2025-09-16       4.59000000
2025-09-17       4.63000000
2025-09-18       4.38000000
2025-09-19       4.50000000
2025-09-22       4.44000000
2025-09-23       4.44000000
2025-09-24       4.45000000
====================================================================================================
⭐ Linha em destaque: dia 0 = data do evento (17/09/2025)

====================================================================================================
SETOR: MINERAÇÃO    |    EVENTO: E2 (2025-09-17)
====================================================================================================
            Dia AURA33_abertura AURA33_fechamento CMIN3_abertura  \
data
2025-09-10   -5     55.96237516       57.83069180     4.81355358
2025-09-11   -4     57.84037219       57.91781537     4.69228188
2025-09-12   -3     57.91781537       56.53351859     4.69228188
2025-09-15   -2     56.77552851       55.98173596     4.74825343
2025-09-16   -1     56.63032255       54.78136673     4.77623920
2025-09-17    0     54.69424316       54.27798608     4.81355358
2025-09-18    1     54.59743918       53.09697765     4.82288217
2025-09-19    2     52.56455581       56.14630271     4.83221076
2025-09-22    3     56.43671462       58.87617467     4.84153934
2025-09-23    4     59.05042181       60.65736772     4.87885372
2025-09-24    5     60.90905804       59.29243174     4.98146823

           CMIN3_fechamento VALE3_abertura VALE3_fechamento
data
2025-09-10       4.71093905    53.84351028      53.94839404
2025-09-11       4.72959624    53.82444050      54.36792910
2025-09-12       4.75758202    54.06281269      54.34885932
2025-09-15       4.74825343    54.80653392      54.82560370
2025-09-16       4.82288217    55.08304567      55.01630145
2025-09-17       4.86019653    54.86374325      55.11165033
2025-09-18       4.82288217    55.14978988      55.00676656
2025-09-19       4.86019653    55.27374342      55.22606898
2025-09-22       4.89751090    55.13072010      55.30234808
2025-09-23       5.00012542    55.30234808      54.98769679
2025-09-24       4.97213964    55.25467364      55.19746432
====================================================================================================
⭐ Linha em destaque: dia 0 = data do evento (17/09/2025)

✅ Aba 'E2' criada
====================================================================================================
SETOR: ENERGIA    |    EVENTO: E3 (2025-09-18)
====================================================================================================
            Dia AXIA3_abertura AXIA3_fechamento CMIG4_abertura  \
data
2025-09-11   -5    35.11905469      35.55679493    10.22760105
2025-09-12   -4    35.03457850      35.55679493    10.11703240
2025-09-15   -3    35.74110661      36.63194639    10.16310267
2025-09-16   -2    37.03128837      36.83161738    10.28288539
2025-09-17   -1    36.64730570      37.47670826    10.32895566
2025-09-18    0    37.39991173      37.63030133    10.50402269
2025-09-19    1    38.04500261      38.82064759    10.44873837
2025-09-22    2    38.45970389      38.19859567    10.38423998
2025-09-23    3    38.19859567      38.93584239    10.40266810
2025-09-24    4    38.87440517      38.93584239    10.58694920
2025-09-25    5    38.99727962      38.70545279    10.55930703

           CMIG4_fechamento CPLE3_abertura CPLE3_fechamento EGIE3_abertura  \
data
2025-09-11      10.17231671    10.70731680      10.74449498    28.76156422
2025-09-12      10.08939023    10.69802225      10.78167316    28.31183539
2025-09-15      10.22760105    10.80955681      10.92109135    28.36102447
2025-09-16      10.31052753    10.93968044      10.96756408    28.65615902
2025-09-17      10.50402269    10.96756408      11.15345500    28.48048369
2025-09-18      10.41188215    11.15345500      11.12557136    28.60696994
2025-09-19      10.40266810    11.13486591      11.32075682    28.78967228
2025-09-22      10.39345405    11.31146228      11.16274954    29.14102293
2025-09-23      10.52245082    11.18133863      11.31146228    29.19723903
2025-09-24      10.55009297    11.33005137      11.21851681    28.90913150
2025-09-25      10.30131349    11.19992772      11.02333135    28.47345668

           EGIE3_fechamento EQTL3_abertura EQTL3_fechamento ISAE4_abertura  \
data
2025-09-11      28.50859175    35.18506122      35.16575528    21.90904987
2025-09-12      28.38210552    34.81824850      34.91477816    21.82416763
2025-09-15      28.61399695    35.19471418      35.29124385    22.03165756
2025-09-16      28.43129461    35.66770952      34.99200190    21.97506937
2025-09-17      28.65615902    35.07887858      35.38777350    22.08824571
2025-09-18      28.80372630    35.29124385      35.33950867    22.25801020
2025-09-19      29.30264422    35.34916163      35.89938070    22.28630428
2025-09-22      29.01453669    35.47465020      35.31054977    22.44663742
2025-09-23      28.97940163    35.35881460      35.94764553    22.18255933